language: ruby
before_install:
  - gem install bundler
cache: bundler
rvm:
  - 2.5.1
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database dashboard_test;' -U postgres
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
